# Numpy Basics

In [1]:
import numpy as np

In [2]:
# checking numpy version:

#the version string is stored under 'version' attribute

In [3]:
import numpy as np
print(np.__version__)

1.23.5


# Create arrays

### 1D Array:

In [4]:
arr=np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
lit=[1,2,3,4,5]
lit

[1, 2, 3, 4, 5]

In [7]:
type(arr)

numpy.ndarray

### 2D Array:

In [11]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [12]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
arr=np.array([[1,2,3,4],[5,6,7]])
arr

C:\Users\vigne\AppData\Local\Temp\ipykernel_10908\1798736792.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[1,2,3,4],[5,6,7]])


array([list([1, 2, 3, 4]), list([5, 6, 7])], dtype=object)

### 3D Array:

In [15]:
arr=np.array([1,2,3,4], ndmin=3)
print(arr)

[[[1 2 3 4]]]


# Higher dimensional array

In [19]:
arr=np.array([1,2,3,4,5], ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]


#### Reshape:  can create another array with different shape, from one array

In [21]:
a=np.array([1,2,3,4,5,6,7,8,9])
arr=a.reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Flattening the arrays

In [22]:
# flattening array means converting a nultidimentional array into a 1d array
# we can use reshape(-1) to do  this

In [25]:
a=np.array([[1,2,3,4],[1,4,5,7],[2,3,5,6]])
arr=a.reshape(-1)
print(arr)

[1 2 3 4 1 4 5 7 2 3 5 6]


## tolist:  convert array to,list

In [27]:
a=np.array([1,2,3,4,5,6,7,8])
lt=a.tolist()
print(type(lt), lt)

<class 'list'> [1, 2, 3, 4, 5, 6, 7, 8]


# Attributes of ndarray

#### ndmin: ndmin atribute returns an integer that tells us how many dimensions the array have

In [31]:
x=np.array(56)
a=np.array([234])
b=np.array([1,2,3,4])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[6,7,8],[2,7,4]]])


In [32]:
print(x.ndim)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
1
2
3


# Size

In [34]:
# Size: return total number of elements in array=(row*col)

In [35]:
print(x.size)
print(a.size)
print(b.size)
print(c.size)
print(d.size)

1
1
4
6
12


# Shape

In [36]:
# shape return (row, col) of the array

In [38]:
print(x.shape)
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(1,)
(4,)
(2, 3)
(1, 4, 3)


# access array elements

In [39]:
# Iterating arrays using nditer():
# Makes easy to iterate through each scalar elements in the array even for complex dimentional as well


In [41]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


In [43]:
d=np.array([[[1,2,3],[4,5,6],[6,7,8],[2,7,4]]])

In [45]:
for i in np.nditer(d):
    print(i)

1
2
3
4
5
6
6
7
8
2
7
4


Iterating with Different step size

In [47]:
arr=np.array([[1,2,3,4],[2,5,7,8]])
for i in np.nditer(arr):
    print(i)
  


1
2
3
4
2
5
7
8


In [48]:
for i in np.nditer(arr[:,::2]):
    print(i)

1
3
2
7


#Enumerated iteration using ndenumerate()

In [49]:
# enumerated means mentioning  sequence number of something one by one

# Sometimes we required corresponding index of the elements while ioterationg
# the ndenumerate( method can be used for those use cases)

In [51]:
arr=np.array([1,2,3,4])
for x,y in np.ndenumerate(arr):
    print(x,y)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [52]:
arr=np.array([4,3,2,1])
for x,y in np.ndenumerate(arr):
    print(x,y)

(0,) 4
(1,) 3
(2,) 2
(3,) 1


# 1. Array Indexing

In [53]:
arr=np.array([1,2,3,4,5,6,7,8])

In [54]:
print(arr[0])

1


In [59]:
# Array creation using Numpy functions:


#Zero

In [62]:
# 1.zeros: Create array with all elements 0, with given dimensions.

a=np.zeros((3,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# Ones

In [63]:
# ones: create array with all elements 1 with given dimention:


In [64]:
a=np.ones((5,4),dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# arrange()function

In [65]:
# arrange function create a sequence of number 

In [69]:
a=np.arange(10)
print(a)

b=np.arange(11,22,dtype='f')
print(b)

[0 1 2 3 4 5 6 7 8 9]
[11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21.]


# linespace

In [ ]:
# 4. linspace: Create 1-D array of linear space numbers / values, by default 50 linspace

In [70]:
p = np.linspace(3,5)
print(p)


[3.         3.04081633 3.08163265 3.12244898 3.16326531 3.20408163
 3.24489796 3.28571429 3.32653061 3.36734694 3.40816327 3.44897959
 3.48979592 3.53061224 3.57142857 3.6122449  3.65306122 3.69387755
 3.73469388 3.7755102  3.81632653 3.85714286 3.89795918 3.93877551
 3.97959184 4.02040816 4.06122449 4.10204082 4.14285714 4.18367347
 4.2244898  4.26530612 4.30612245 4.34693878 4.3877551  4.42857143
 4.46938776 4.51020408 4.55102041 4.59183673 4.63265306 4.67346939
 4.71428571 4.75510204 4.79591837 4.83673469 4.87755102 4.91836735
 4.95918367 5.        ]


## Numpy function

In [74]:
# insert

a=np.array([1,2,3,4,5])
a=np.insert(a,5,100)
print(a)

[  1   2   3   4   5 100]


In [77]:
# append : insert values at the end of the array

a=np.array([2,3,4,5])
a=np.append(a,300)

print(a)

[  2   3   4   5 300]


In [78]:
## ceil():

# closest upper int value to the given float number

a=np.array([1.2,3.5,6.7,8.4,12.6])
a=np.ceil(a)
print(a)


[ 2.  4.  7.  9. 13.]


In [80]:
## Floor

# closest lower int value to the given number

a=np.array([1.2,3.5,6.7,8.4,12.6])
a=np.floor(a)
print(a)

[ 1.  3.  6.  8. 12.]


In [81]:
# around()

a=np.array([1.2,3.5,6.7,8.4,12.6])
a=np.around(a)
print(a)

[ 1.  4.  7.  8. 13.]


In [82]:
#argmax():  return max(index)
# return index of the max element in the array

a=np.array([1.2,3.5,6.7,8.4,12.6])
a=np.argmax(a)
print(a)

4


In [83]:
# argmin:  return min(index) of the element in the array

a=np.array([1.2,3.5,6.7,8.4,12.6])
a=np.argmin(a)
print(a)

0


## where 

In [84]:
# where is similar for the if else condition
# return indices of values, for which the given condition is statisfied.

#np.where(condition, true(replace with this value), false(replace with this value))

In [86]:
a=np.array([2,3,4,5,6,7,8])
a=np.where(a>5,1,0)
print(a)

[0 0 0 0 1 1 1]


# copy

In [87]:
a

array([0, 0, 0, 0, 1, 1, 1])

In [88]:
b=a.copy()

In [89]:
b

array([0, 0, 0, 0, 1, 1, 1])

# view

In [91]:
a.view()

array([0, 0, 0, 0, 1, 1, 1])

# Numpy joining array

# row wise joining

In [92]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,5])

join=np.concatenate((a,b),axis=0)

In [93]:
join

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 5])

In [96]:
a=np.array([[1,2,3,4,5],[6,7,8,9,5]])
b=np.array([[6,7,8,9,5],[1,2,3,4,5]])

join2=np.concatenate((a,b),axis=1)
join2

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 5],
       [6, 7, 8, 9, 5, 1, 2, 3, 4, 5]])