## Multiple Linear Regression

In [102]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Read csv

data=pd.read_csv(r"C:\Users\vigne\OneDrive\Desktop\sathish workbench\bi\New folder\Student_Performance.csv")

In [4]:
data.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [5]:
data.tail

<bound method NDFrame.tail of       Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sam

In [6]:
data.shape

(10000, 6)

In [7]:
data.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Hours Studied                     10000 non-null  int64  
 1   Previous Scores                   10000 non-null  int64  
 2   Extracurricular Activities        10000 non-null  object 
 3   Sleep Hours                       10000 non-null  int64  
 4   Sample Question Papers Practiced  10000 non-null  int64  
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB


In [9]:
data.describe()

Hours Studied  Previous Scores   Sleep Hours  \
count   10000.000000     10000.000000  10000.000000   
mean        4.992900        69.445700      6.530600   
std         2.589309        17.343152      1.695863   
min         1.000000        40.000000      4.000000   
25%         3.000000        54.000000      5.000000   
50%         5.000000        69.000000      7.000000   
75%         7.000000        85.000000      8.000000   
max         9.000000        99.000000      9.000000   

       Sample Question Papers Practiced  Performance Index  
count                      10000.000000       10000.000000  
mean                           4.583300          55.224800  
std                            2.867348          19.212558  
min                            0.000000          10.000000  
25%                            2.000000          40.000000  
50%                            5.000000          55.000000  
75%                            7.000000          71.000000  
max                            9.000000         100.000000

In [14]:
data.duplicated().sum()

127

In [15]:
# Remove duplicated rows based on all columns

df=data.drop_duplicates()

In [16]:
df

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[9873 rows x 6 columns]

In [17]:
df.shape

(9873, 6)

In [22]:
df.describe()

Hours Studied  Previous Scores  Sleep Hours  \
count    9873.000000      9873.000000  9873.000000   
mean        4.992100        69.441102     6.531652   
std         2.589081        17.325601     1.697683   
min         1.000000        40.000000     4.000000   
25%         3.000000        54.000000     5.000000   
50%         5.000000        69.000000     7.000000   
75%         7.000000        85.000000     8.000000   
max         9.000000        99.000000     9.000000   

       Sample Question Papers Practiced  Performance Index  
count                       9873.000000        9873.000000  
mean                           4.583004          55.216651  
std                            2.867202          19.208570  
min                            0.000000          10.000000  
25%                            2.000000          40.000000  
50%                            5.000000          55.000000  
75%                            7.000000          70.000000  
max                            9.000000         100.000000

In [23]:
# EDA- Explanatory data analysis

In [24]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [26]:
df['Hours Studied'].unique()

array([7, 4, 8, 5, 3, 6, 2, 1, 9], dtype=int64)

In [28]:
df['Previous Scores'].unique()

array([99, 82, 51, 52, 75, 78, 73, 45, 77, 89, 91, 79, 47, 72, 83, 54, 96,
       74, 85, 61, 62, 84, 94, 90, 44, 70, 67, 97, 59, 55, 68, 63, 46, 76,
       43, 81, 93, 98, 48, 92, 64, 88, 60, 87, 40, 69, 80, 95, 49, 50, 53,
       71, 56, 58, 66, 65, 57, 41, 42, 86], dtype=int64)

In [29]:
df['Extracurricular Activities'].unique()

array(['Yes', 'No'], dtype=object)

In [30]:
df['Extracurricular Activities'].nunique()

2

In [31]:
df['Extracurricular Activities'].value_counts()

No     4986
Yes    4887
Name: Extracurricular Activities, dtype: int64

In [32]:
df['Sleep Hours'].unique()

array([9, 4, 7, 5, 8, 6], dtype=int64)

In [33]:
df['Sample Question Papers Practiced'].unique()

array([1, 2, 5, 6, 0, 8, 3, 4, 9, 7], dtype=int64)

In [63]:
#df['Extracurricular Activities']=df['Extracurricular Activities'].replace({"No":0, "Yes":1})

#df['Extracurricular Activities']=df['Extracurricular Activities'].replace({"No":0, "Yes":1})

df = pd.get_dummies(df, columns=['Extracurricular Activities'], drop_first=True, dtype=int)



In [64]:
df.head()

Hours Studied  Previous Scores  Sleep Hours  \
0              7               99            9   
1              4               82            4   
2              8               51            7   
3              5               52            5   
4              7               75            8   

   Sample Question Papers Practiced  Performance Index  \
0                                 1               91.0   
1                                 2               65.0   
2                                 2               45.0   
3                                 2               36.0   
4                                 5               66.0   

   Extracurricular Activities_1  
0                             1  
1                             0  
2                             1  
3                             1  
4                             0

In [65]:
##  train test split

X=df.drop('Performance Index', axis=1)
Y=df['Performance Index']

In [66]:
X


Hours Studied  Previous Scores  Sleep Hours  \
0                 7               99            9   
1                 4               82            4   
2                 8               51            7   
3                 5               52            5   
4                 7               75            8   
...             ...              ...          ...   
9995              1               49            4   
9996              7               64            8   
9997              6               83            8   
9998              9               97            7   
9999              7               74            8   

      Sample Question Papers Practiced  Extracurricular Activities_1  
0                                    1                             1  
1                                    2                             0  
2                                    2                             1  
3                                    2                             1  
4                                    5                             0  
...                                ...                           ...  
9995                                 2                             1  
9996                                 5                             1  
9997                                 5                             1  
9998                                 0                             1  
9999                                 1                             0  

[9873 rows x 5 columns]

In [67]:
X

Hours Studied  Previous Scores  Sleep Hours  \
0                 7               99            9   
1                 4               82            4   
2                 8               51            7   
3                 5               52            5   
4                 7               75            8   
...             ...              ...          ...   
9995              1               49            4   
9996              7               64            8   
9997              6               83            8   
9998              9               97            7   
9999              7               74            8   

      Sample Question Papers Practiced  Extracurricular Activities_1  
0                                    1                             1  
1                                    2                             0  
2                                    2                             1  
3                                    2                             1  
4                                    5                             0  
...                                ...                           ...  
9995                                 2                             1  
9996                                 5                             1  
9997                                 5                             1  
9998                                 0                             1  
9999                                 1                             0  

[9873 rows x 5 columns]

In [68]:
Y

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ... 
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 9873, dtype: float64

In [69]:
from sklearn.model_selection import train_test_split

In [121]:
X=pd.DataFrame(X)
Y=pd.DataFrame(Y)

In [122]:
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, random_state=7, test_size=0.2)

In [123]:
X_train=pd.DataFrame(X_train)
X_test=pd.DataFrame(X_test)
Y_train=pd.DataFrame(Y_train)
Y_test=pd.DataFrame(Y_test)

In [124]:
Y_test

Performance Index
3265               59.0
175                45.0
4225               48.0
4653               64.0
1321               24.0
...                 ...
541                64.0
5355               34.0
2544               60.0
3888               70.0
1935               46.0

[1975 rows x 1 columns]

In [92]:
#X_train.shape
X_test.shape
# Y_train.shape
# Y_test.shape

(1975, 5)

In [74]:
df.columns

Index(['Hours Studied', 'Previous Scores', 'Sleep Hours',
       'Sample Question Papers Practiced', 'Performance Index',
       'Extracurricular Activities_1'],
      dtype='object')

In [ ]:
# df['Extracurricular Activities']=df['Extracurricular Activities'].replace({'No':0, "Yes":1})

In [54]:
## Model building

In [104]:
from sklearn.linear_model import LinearRegression

In [125]:
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [131]:
## predict

Y_pred=pd.DataFrame(regressor.predict(X_test))

In [107]:
## Model evalution

In [108]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [132]:
Y_pred.shape

(1975, 1)

In [134]:
type(Y_pred)

pandas.core.frame.DataFrame

In [118]:
Y_test.shape

(1975, 1)

In [111]:
mse=mean_squared_error(Y_test,Y_pred)

In [112]:
mse

4.276228141485038

In [113]:
r2=r2_score(Y_test,Y_pred)

In [114]:
r2

0.9879370299201616

In [115]:
mbe=mean_absolute_error(Y_test,Y_pred)

In [116]:
mbe

1.6344251815821638